{
  'global':
    {
      'scrape_interval': '15s',
      'evaluation_interval': '15s',
      'external_labels': { 'monitor': 'server-local' },
    },
  'rule_files':
    ['/etc/prometheus/alerts.yml', '/etc/prometheus/expected-probes.yml'],
  'alerting':
    {
      'alertmanagers':
        [{ 'static_configs': [{ 'targets': ['alertmanager:9093'] }] }],
    },
  'scrape_configs':
    [
      {
        'job_name': 'traefik',
        'static_configs': [{ 'targets': ['traefik:8082'] }],
        'metric_relabel_configs':
          [
            {
              'source_labels': ['router'],
              'regex': 'app@file|assets@file|api@file|app-https@file|assets-https@file|api-https@file',
              'target_label': 'site',
              'replacement': 'haih.site',
            },
          ],
      },
      {
        'job_name': 'app',
        'file_sd_configs': [{ 'files': ['/etc/prometheus/apps.json'] }],
      },
      {
        'job_name': 'host',
        'static_configs': [{ 'targets': ['node-exporter:9100'] }],
      },
      {
        'job_name': 'prometheus',
        'static_configs': [{ 'targets': ['localhost:9090'] }],
      },
      { 'job_name': 'loki', 'static_configs': [{ 'targets': ['loki:3100'] }] },
      {
        'job_name': 'alloy',
        'static_configs': [{ 'targets': ['alloy:12345'] }],
      },
      {
        'job_name': 'alertmanager',
        'static_configs': [{ 'targets': ['alertmanager:9093'] }],
      },
      {
        'job_name': 'probe',
        'scrape_interval': '30s',
        'scrape_timeout': '10s',
        'metrics_path': '/probe',
        'relabel_configs':
          [
            {
              'source_labels': ['__address__'],
              'target_label': '__param_target',
            },
            { 'source_labels': ['module'], 'target_label': '__param_module' },
            { 'source_labels': ['__param_target'], 'target_label': 'instance' },
            { 'target_label': '__address__', 'replacement': 'blackbox:9115' },
          ],
        'file_sd_configs': [{ 'files': ['/etc/prometheus/probes.json'] }],
      },
    ],
}
